# Jupyter Notebook zur Erklärung mathematischer Matrizen
Dieses Notebook führt grundlegende Konzepte zu Matrizen, deren Eigenschaften und Operationen ein. 
Es werden verschiedene Begriffe erklärt und mit Beispielen in Python umgesetzt.

## 1. Einführung in Mathematische Matrizen
Eine Matrix ist ein rechteckiges Array von Zahlen, das aus Zeilen und Spalten besteht.
Jede Zahl in einer Matrix wird als "Element" oder "Koeffizient" bezeichnet.

In [2]:
import numpy as np

# Beispielmatrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Matrix anzeigen
print("Beispielmatrix:")
print(matrix)

Beispielmatrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Begriffe:
- **Matrix**: Ein rechteckiges Anordnung von Zahlen in Zeilen und Spalten.
- **Zeile**: Eine horizontale Reihe von Elementen in der Matrix.
- **Spalte**: Eine vertikale Reihe von Elementen in der Matrix.
- **Element (Koeffizient)**: Ein einzelner Eintrag in der Matrix.

Die oben gezeigte Matrix hat 3 Zeilen und 3 Spalten. Jedes Element ist eine Zahl.

In [3]:
# Die Anzahl der Zeilen und Spalten einer Matrix wird als "Größe" der Matrix bezeichnet.
print("Größe der Matrix:", matrix.shape[0], "Zeilen und", matrix.shape[1], "Spalten")

# Wir können auch auf bestimmte Zeilen, Spalten oder Elemente zugreifen:
print("Erste Zeile:", matrix[0])
print("Erste Spalte:", matrix[:, 0])
print("Erstes Element:", matrix[0, 0])

Größe der Matrix: 3 Zeilen und 3 Spalten
Erste Zeile: [1 2 3]
Erste Spalte: [1 4 7]
Erstes Element: 1


## 2. Eigenschaften von Matrizen
Matrizen haben verschiedene Eigenschaften, die ihre Struktur und ihr Verhalten beschreiben.
Dazu gehören Symmetrie, Rang, Determinante und Eigenwerte/Eigenvektoren.

### Symmetrische und Antisymmetrische Matrizen:
- **Symmetrische Matrix**: Eine Matrix ist symmetrisch, wenn sie gleich ihrer transponierten Matrix ist (A = A^T).
- **Antisymmetrische Matrix**: Eine Matrix ist antisymmetrisch, wenn die transponierte Matrix das negative der Originalmatrix ist (A = -A^T).

In [4]:
# Symmetrische Matrix: A = A^T (Transponierte Matrix)
symmetrische_matrix = np.array([[1, 2], [2, 1]])
print("Symmetrische Matrix:\n", symmetrische_matrix)

# Antisymmetrische Matrix: A = -A^T
antisymmetrische_matrix = np.array([[0, 2], [-2, 0]])
print("Antisymmetrische Matrix:\n", antisymmetrische_matrix)

Symmetrische Matrix:
 [[1 2]
 [2 1]]
Antisymmetrische Matrix:
 [[ 0  2]
 [-2  0]]


### Weitere Eigenschaften:
- **Rang**: Der Rang einer Matrix gibt die Anzahl der linear unabhängigen Zeilen oder Spalten an.
- **Determinante**: Eine Zahl, die Eigenschaften einer quadratischen Matrix beschreibt. Eine Matrix mit einer Determinante von 0 ist nicht invertierbar.

In [5]:
# Der Rang einer Matrix gibt die Anzahl der linear unabhängigen Zeilen oder Spalten an.
print("Rang der Beispielmatrix:", np.linalg.matrix_rank(matrix))

# Die Determinante einer Matrix gibt Informationen darüber, ob eine Matrix invertierbar ist.
print("Determinante der Beispielmatrix:", np.linalg.det(matrix))

Rang der Beispielmatrix: 2
Determinante der Beispielmatrix: 0.0


### Eigenwerte und Eigenvektoren:
- **Eigenwerte**: Werte, die angeben, wie stark ein Eigenvektor beim Anwenden der Matrix gestreckt oder gestaucht wird.
- **Eigenvektoren**: Richtungen, die durch die Matrix nicht verändert werden, außer durch Streckung oder Stauchung.

In [6]:
# Eigenwerte und Eigenvektoren einer Matrix sind spezielle Vektoren und Skalare, die die Matrix charakterisieren.
eigenwerte, eigenvektoren = np.linalg.eig(symmetrische_matrix)
print("Eigenwerte der symmetrischen Matrix:", eigenwerte)
print("Eigenvektoren der symmetrischen Matrix:\n", eigenvektoren)

Eigenwerte der symmetrischen Matrix: [ 3. -1.]
Eigenvektoren der symmetrischen Matrix:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## 3. Relationen zwischen Matrizen
Matrizen können gleich sein, wenn alle ihre Elemente übereinstimmen.

### Relationen:
- **Gleichheit von Matrizen**: Zwei Matrizen sind gleich, wenn alle ihre entsprechenden Elemente übereinstimmen.
- **Kleiner**: Eine Matrix A ist kleiner als eine Matrix B, wenn alle Elemente von A kleiner als die entsprechenden Elemente von B sind.

In [7]:
# Beispiel zur Gleichheit von Matrizen
matrix_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Ist matrix gleich matrix_2?:", np.array_equal(matrix, matrix_2))

# Beispiel zur Überprüfung, ob eine Matrix kleiner ist
matrix_3 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print("Ist matrix_3 kleiner als matrix?:", np.all(matrix_3 < matrix))

Ist matrix gleich matrix_2?: True
Ist matrix_3 kleiner als matrix?: True


## 4. Spezielle Matrizen
Es gibt bestimmte Matrizen mit speziellen Eigenschaften, wie die Einheitsmatrix, die Nullmatrix oder die Diagonalmatrix.

### Spezielle Matrizen:
- **Einheitsmatrix**: Eine quadratische Matrix, bei der alle Diagonalelemente 1 und alle anderen Elemente 0 sind.
- **Nullmatrix**: Eine Matrix, bei der alle Elemente 0 sind.
- **Diagonalmatrix**: Eine Matrix, bei der alle Elemente außerhalb der Hauptdiagonale 0 sind.

In [8]:
# Beispiele für spezielle Matrizen

# Einheitsmatrix (Identitätsmatrix)
einheitsmatrix = np.eye(3)
print("Einheitsmatrix (3x3):\n", einheitsmatrix)

# Nullmatrix
nullmatrix = np.zeros((3, 3))
print("Nullmatrix (3x3):\n", nullmatrix)

# Diagonalmatrix
diagonalmatrix = np.diag([1, 2, 3])
print("Diagonalmatrix (3x3):\n", diagonalmatrix)

Einheitsmatrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Nullmatrix (3x3):
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Diagonalmatrix (3x3):
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


## 5. Operationen auf Matrizen
Matrizen können addiert, subtrahiert und multipliziert werden. Hier sind einige grundlegende Operationen:

### Operationen:
- **Matrizenaddition**: Zwei Matrizen werden addiert, indem die entsprechenden Elemente addiert werden.
- **Skalarmultiplikation**: Jede Komponente der Matrix wird mit einem Skalar multipliziert.
- **Matrizenmultiplikation**: Das Produkt zweier Matrizen wird durch Zeilen-Spalten-Multiplikation berechnet.

In [9]:
# Matrizenaddition
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])
matrix_add = matrix_A + matrix_B
print("Addition von Matrix A und B:\n", matrix_add)

# Skalarmultiplikation
skalare_matrix = 2 * matrix_A
print("Skalarmultiplikation von Matrix A mit 2:\n", skalare_matrix)

# Matrizenmultiplikation
matrix_mult = np.dot(matrix_A, matrix_B)
print("Multiplikation von Matrix A und B:\n", matrix_mult)

Addition von Matrix A und B:
 [[ 6  8]
 [10 12]]
Skalarmultiplikation von Matrix A mit 2:
 [[2 4]
 [6 8]]
Multiplikation von Matrix A und B:
 [[19 22]
 [43 50]]


## 6. Berechnung der Determinante
Die Determinante einer Matrix kann auf verschiedene Weise berechnet werden.

### Determinanten:
- **Sarrus-Regel**: Eine spezielle Regel zur Berechnung der Determinante von 3x3-Matrizen.
- **Entwicklungssatz von Laplace**: Eine Methode zur Berechnung der Determinante einer Matrix durch die Zerlegung in kleinere Matrizen.

In [10]:
# Sarrus-Regel (für 3x3-Matrizen)
matrix_C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix C:\n", matrix_C)
print("Die Determinante von Matrix C:", np.linalg.det(matrix_C))

# Entwicklungssatz von Laplace (hier für eine 2x2 Matrix)
matrix_D = np.array([[1, 2], [3, 4]])
det_D = matrix_D[0, 0] * matrix_D[1, 1] - matrix_D[0, 1] * matrix_D[1, 0]
print("Die Determinante von Matrix D (2x2):", det_D)

Matrix C:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Die Determinante von Matrix C: 0.0
Die Determinante von Matrix D (2x2): -2
